export const AGENDA_PANEL_HEIGHT_PX = 620;
export const AGENDA_PANEL_HEIGHT_EXPANDED_PX = 720;
export const AGENDA_TODO_COLUMN_WIDTH_PX = 360;
export const AGENDA_TODO_COLUMN_WIDTH_EXPANDED_PX = 520;
export const AGENDA_CONTAINER_MAX_WIDTH_EXPANDED_PX = 1680;
